spring:
  profiles:
    active: "test"
    include: "private"
  datasource:
    url: "jdbc:${config.database.dialect}://${config.database.host}:${config.database.port}/${config.database.name}"
    username: "${config.database.username}"
    password: "${config.database.password}"
    driver-class-name: "org.postgresql.Driver"
  servlet:
    multipart:
      max-file-size: "1GB"
      max-request-size: "1GB"
