config:
  database:
    dialect: "postgresql"
    host: "localhost"
    port: 5432
    name: "fmi_materials"
  security:
    password_hash:
      iterations: 10
      algorithm: "bcrypt"
  logger:
    level: "TRACE"