spring:
  profiles:
<<<<<<< HEAD:backend/src/main/resources/application.yaml
    active: "dev"
    include: "private"
=======
    active: "local"
>>>>>>> added logging from lab:FMI-Materials/src/main/resources/application.yaml
  datasource:
    url: "jdbc:${config.database.dialect}://${config.database.host}:${config.database.port}/${config.database.name}"
    username: "${database.username}"
    password: "${database.password}"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  flyway:
    url: "jdbc:${config.database.dialect}://${config.database.host}:${config.database.port}/${config.database.name}"
    user: "${database.username}"
    password: "${database.password}"
    schemas: "public"
    defaultSchema: "public"
    createSchemas: "true"
  servlet:
    multipart:
      max-file-size: "1GB"
      max-request-size: "1GB"
