spring:
  profiles:
    active: "dev"
  datasource:
    url: "jdbc:${config.database.dialect}://${config.database.host}:${config.database.port}/${config.database.name}"
    username: "postgres"
    password: "mddionisie"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  flyway:
    url: "jdbc:${config.database.dialect}://${config.database.host}:${config.database.port}/${config.database.name}"
    user: "postgres"
    password: "mddionisie"
    schemas: "public"
    defaultSchema: "public"
    createSchemas: "true"