spring:
  profiles:
    active: "dev"
    include: "private"
  datasource:
    url: "jdbc:${config.database.dialect}://${config.database.host}:${config.database.port}/${config.database.name}"
    username: "${config.database.username}"
    password: "${config.database.password}"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  flyway:
    url: "jdbc:${config.database.dialect}://${config.database.host}:${config.database.port}/${config.database.name}"
    user: "${config.database.username}"
    password: "${config.database.password}"
    schemas: "public"
    defaultSchema: "public"
    createSchemas: "true"
